export const SET_START_GAME = 'SET_START_GAME';
export const GET_CARDS_LIST_REQUESTED = 'GET_CARDS_LIST_REQUESTED';
export const GET_CARDS_LIST_SUCCESS = 'GET_CARDS_LIST_SUCCESS';
export const GET_CARDS_LIST_FAILED = 'GET_CARDS_LIST_FAILED';
export const SET_FLIP_CARD = 'SET_FLIP_CARD';
